Reflexivity rule
FMFI-UK-1-AIN-412/tableauEditor pull request #15
Opened 2020-11-02 16:27 UTC by MatejKomlossy

2020-11-20 18:00 UTC, crnkjck requested changes

2020-11-20 18:00 UTC, crnkjck commented on src/Helpers/Exporting/Json/Encode.elm
> +jsonNode : { b | id : Int, references : List { a | str : String }, value : String, gui : GUI } -> Value
This looks like an auto-generated type. There should probably be `Tableau.Node` here.

2020-11-20 18:00 UTC, crnkjck commented on src/Helpers/Helper.elm
> +    (List.length (Zipper.zNode z).references == 0) && ((Zipper.zNode z).value /= "")
`List.isEmpty` is easier to read than `List.length … == 0`

2020-11-20 18:00 UTC, crnkjck commented on src/Validate.elm
>  isValidNodeRef : Zipper.Zipper -> Result (List { msg : String, typ : ProblemType, zip : Zipper.Zipper }) Zipper.Zipper
Another ugly auto-generated type. Use `Problem` instead, fix everywhere.

2020-11-20 18:00 UTC, crnkjck commented on src/Validate.elm
> +isPointingOnSelf : Zipper.Zipper -> Bool --rozdelit na first a second
There shouldn't be note-to-self comments in the merged code. Can you resolve this now? Since there are no two-reference nodes yet, you can either leave this be for now without the comment (you resolve this issue just as well without this comment), or you can right now generalize this function to one that also takes a ref-extracting function, i.e., one type `(Zipper.Zipper -> Ref) -> Zipper.Zipper -> Bool`. Such a function can then check if any reference extracted by its first argument is to the node itself.

2020-11-20 18:00 UTC, crnkjck commented on src/Zipper.elm
> +getFixedRef : Zipper -> Ref -> Ref
Why did you switch the arguments? It's usually better to have the complex data structure as the last argument.

2020-11-20 19:07 UTC, MatejKomlossy commented on src/Zipper.elm
> +getFixedRef : Zipper -> Ref -> Ref
To be able to map through a list of references

2020-11-22 10:32 UTC, MatejKomlossy commented on src/Zipper.elm
> +getFixedRef : Zipper -> Ref -> Ref
Ok i realized i can do that with the original order of arguments as well, sorry it is fixed now.

2020-11-25 12:53 UTC, crnkjck approved these changes
Seems fine to me now. There were some not-so-fortunate decisions made in the past, apparently, but we can leave them be for now. :)

2020-11-25 13:16 UTC, merged